# Generated by Django 3.2.9 on 2021-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kisi', 'verbose_name_plural': 'Kisiler'},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active_slider_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Butce'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(verbose_name='Zaman'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Ozet'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='Cinsiyyet'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.CharField(max_length=255, verbose_name='Film ArkaPlan Resmi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_name',
            field=models.CharField(max_length=255, verbose_name='Film Resmi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Dil'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(to='movies.Person', verbose_name='Filmde Yer Alan Karakterler'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Baslik'),
        ),
        migrations.AlterField(
            model_name='person',
            name='duty_type',
            field=models.CharField(choices=[('1', 'Gorevli'), ('2', 'Oyuncu'), ('3', 'Yonetmen'), ('4', 'Senarist')], max_length=1, verbose_name='Gorev'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadin')], max_length=1, verbose_name='Cinsiyyet'),
        ),
    ]
