# Generated by Django 3.2.9 on 2021-12-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211201_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_active_home_page',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='is_active_slider_page',
            new_name='is_active_home',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='Film Tipi'),
        ),
    ]
