# Generated by Django 3.2.9 on 2021-12-11 04:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211211_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
