# Generated by Django 3.2.9 on 2021-12-11 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_commentmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmovie',
            name='rating',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
