# Generated by Django 3.2.9 on 2021-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_commentmovie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmovie',
            name='rating',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commentmovie',
            name='your_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
