# Generated by Django 3.2.9 on 2021-12-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20211212_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmovie',
            name='date_comments',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
