# Generated by Django 3.2.9 on 2021-12-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_commentmovie_date_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmovie',
            options={'ordering': ['-date_comments']},
        ),
    ]
