# Generated by Django 3.2.9 on 2021-12-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('movies', '0015_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmovie',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.auth'),
        ),
    ]
