# Generated by Django 3.2.9 on 2021-12-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_commentmovie_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmovie',
            name='full_name',
        ),
    ]
