# Generated by Django 3.2.9 on 2021-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_remove_commentmovie_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmovie',
            name='profile',
        ),
        migrations.AddField(
            model_name='commentmovie',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Yorum Yapan'),
            preserve_default=False,
        ),
    ]
